name: GH-Pages Deploy
on:
  push:
    branches: [ master ]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: |
          wget -O reveal-yaml.zip https://github.com/KmolYuan/reveal-yaml-rs/releases/latest/download/reveal-yaml-linux-amd64.zip
          unzip reveal-yaml.zip
          chmod +x rym
          ./rym pack
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: package
          CLEAN: true
